name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # Build and Test Job
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm run type-check
        continue-on-error: true # Allow deployment even with type errors for now

      - name: Build application
        run: pnpm build
        env:
          SPOTIFY_CLIENT_ID: "test_client_id"
          SPOTIFY_CLIENT_SECRET: "test_client_secret"
          NEXTAUTH_SECRET: "test_nextauth_secret"
          NEXTAUTH_URL: "http://localhost:3000"
          SPOTIFY_REDIRECT_URI: "http://localhost:3000/api/auth/callback/spotify"
          ITUNES_API_URL: "https://itunes.apple.com/search"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-files
          path: .next/
          retention-days: 1

  # Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  # Deploy to Vercel Preview (PR only)
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next/

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prebuilt'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: true

  # Deploy to Vercel Production (main branch only)
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next/

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        id: deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --prebuilt'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Update deployment status
        run: |
          echo "Deployment URL: ${{ steps.deploy.outputs.preview-url }}"
          echo "Production deployment completed successfully!"

  # Health check after production deployment
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Wait for deployment
        run: sleep 30

      - name: Health check
        run: |
          HEALTH_URL="https://music-transfer-lac.vercel.app"
          echo "Checking health of: $HEALTH_URL"
          
          # Check if the site is responding
          response=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" || echo "000")
          
          if [[ "$response" -eq 200 ]]; then
            echo "✅ Health check passed - Site is responding"
          else
            echo "❌ Health check failed - HTTP $response"
            exit 1
          fi

  # Notify on deployment success/failure
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [deploy-production, health-check]
    if: always() && (github.ref == 'refs/heads/main' && github.event_name == 'push')
    
    steps:
      - name: Notify success
        if: needs.deploy-production.result == 'success' && needs.health-check.result == 'success'
        run: |
          echo "🚀 Deployment successful!"
          echo "Live URL: https://music-transfer-lac.vercel.app"

      - name: Notify failure
        if: needs.deploy-production.result == 'failure' || needs.health-check.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the logs for more information."